deneme/Models/ErrorViewModel.cs
namespace deneme.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

deneme/Models/Sti.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace deneme.Models
{
    [Table("STI")]
    public partial class Sti
    {
        [Column("ID")]
        public int Id { get; set; }
        [Key]
        public short IslemTur { get; set; }
        [Key]
        [StringLength(16)]
        [Unicode(false)]
        public string EvrakNo { get; set; } = null!;
        [Key]
        public int Tarih { get; set; }
        [StringLength(30)]
        [Unicode(false)]
        public string MalKodu { get; set; } = null!;
        [Column(TypeName = "numeric(25, 6)")]
        public decimal Miktar { get; set; }
        [Column(TypeName = "numeric(25, 6)")]
        public decimal Fiyat { get; set; }
        [Column(TypeName = "numeric(25, 6)")]
        public decimal Tutar { get; set; }
        [StringLength(4)]
        [Unicode(false)]
        public string Birim { get; set; } = null!;
    }
}

deneme/Models/Stk.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace deneme.Models
{
    [Table("STK")]
    public partial class Stk
    {
        [Column("ID")]
        public int Id { get; set; }
        [Key]
        [StringLength(30)]
        [Unicode(false)]
        public string MalKodu { get; set; } = null!;
        [StringLength(50)]
        [Unicode(false)]
        public string MalAdi { get; set; } = null!;

    }
}

deneme/Controllers/HomeController.cs
using deneme.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace deneme.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

deneme/Controllers/StiController.cs
using deneme.Data;
using Microsoft.AspNetCore.Mvc;

namespace deneme.Controllers
{
    public class StiController : Controller
    {
        private readonly TestContext db;

        public StiController(TestContext testContext)
        {
            db = testContext;
        }
        public IActionResult Index()
        {
            db.Stis.OrderByDescending(a => a.Tarih);
            return View(db.Stis.ToList());
        }
    }
}

deneme/Controllers/StkController.cs
using deneme.Data;
using deneme.Models;
using Microsoft.AspNetCore.Mvc;

namespace deneme.Controllers
{
    public class StkController : Controller
    {
        private readonly TestContext db;

        public StkController(TestContext testContext)
        {
            db = testContext;
        }
        public IActionResult Index()
        {
            
            return View(db.Stks.ToList());
        }
        
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Stk model)
        {
            db.Add(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            //db.Stks.Where(a => a.Id == id);
            return View(db.Stks.FirstOrDefault(a=>a.Id==id));
        }
        [HttpPost]
        public IActionResult Delete(Stk model)
        {
            Stk stk = db.Stks.FirstOrDefault(a=>a.Id==model.Id);
            db.Remove(stk);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            return View(db.Stks.FirstOrDefault(a => a.Id == id));
        }
        [HttpPost]
        public IActionResult Edit(Stk model)
        {
            //mal kodu pk oldugu için hata fırlatıyor ya mal kodu değiştirmezsek hata fırlatmaz
            var yd = db.Stks.FirstOrDefault(a=>a.Id==model.Id);
            yd.Id = model.Id;
            yd.MalKodu = model.MalKodu;
            yd.MalAdi=model.MalAdi;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

deneme/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

deneme/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - deneme</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/deneme.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">deneme</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sti" asp-action="Index">Stilist</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stk" asp-action="Index">StkList</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - deneme - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

deneme/Views/Sti/Index.cshtml
@model IEnumerable<deneme.Models.Sti>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MalKodu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Miktar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fiyat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tutar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Birim)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MalKodu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Miktar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fiyat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tutar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Birim)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

deneme/Views/Stk/Create.cshtml
@model deneme.Models.Stk

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Stk</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MalKodu" class="control-label"></label>
                <input asp-for="MalKodu" class="form-control" />
                <span asp-validation-for="MalKodu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MalAdi" class="control-label"></label>
                <input asp-for="MalAdi" class="form-control" />
                <span asp-validation-for="MalAdi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

deneme/Views/Stk/Delete.cshtml
@model deneme.Models.Stk

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3> Are you sure you want to delete this?</h3>
<div>
    <h4>Stk</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MalAdi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MalAdi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MalKodu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MalKodu)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

deneme/Views/Stk/Edit.cshtml
@model deneme.Models.Stk

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Stk</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            
            <input type="hidden" asp-for="Id" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MalAdi" class="control-label"></label>
                <input asp-for="MalAdi" class="form-control" />
                <span asp-validation-for="MalAdi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MalKodu" class="control-label"></label>
                <input asp-for="MalKodu" class="form-control" />
                <span asp-validation-for="MalKodu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

deneme/Views/Stk/Index.cshtml
@model IEnumerable<deneme.Models.Stk>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MalAdi)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.MalKodu)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MalAdi)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.MalKodu)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> | |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>